spring.datasource.url=jdbc:mysql://localhost:3307/hotel_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
server.address=0.0.0.0
# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=johrisaaransh28@gmail.com        
spring.mail.password=sgbz dwvw zbex hanf          
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true